name: Regression End-to-end tests
on: push
jobs:
  addtocart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: addtocart run
        uses: cypress-io/github-action@v6
        with:
           command: npm run test:addToCart
  register-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: register run
        uses: cypress-io/github-action@v6
        with:
            command: npm run test:register